#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <time.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <sys/stat.h>
#include <ncurses.h>
#include <sys/wait.h>
#include <dirent.h>
#include <ctype.h>
#include <dlfcn.h>

#include "store/store.h"
#include "utils/cmd.h"
#include "utils/disk.h"
#include "utils/deps.h"
#include "ui/ui.h"
#include "ui/modal.h"
#include "ui/interfaces.h"
#include "steps/steps.h"
#include "steps/locale.h"
#include "steps/disk.h"
#include "steps/partition/table.h"
#include "steps/partition/dialogs.h"
#include "steps/partition/partition.h"
#include "steps/confirm.h"
#include "install/install.h"
#include "install/partitions.h"
#include "install/rootfs.h"
#include "install/bootloader.h"
#include "install/locale.h"
